services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:prod
    volumes:
      - ./data:/app/data
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:prod
    command: ["celery", "-A", "app.workers", "worker", "--loglevel=info"]
    volumes:
      - ./data:/app/data
    env_file: .env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:prod
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: caseforge
      POSTGRES_PASSWORD: caseforge
      POSTGRES_DB: caseforge
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_buffers=256MB", "-c", "work_mem=8MB"]

volumes:
  pg_data:
