services:
  backend:
    build: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
    volumes: [ "./backend:/code" ]
    ports: [ "8000:8000" ]
    env_file: .env

  frontend:
    build: ./frontend
    command: ["npm", "run", "dev", "-w", "web"]
    volumes: [ "./frontend:/app" ]
    ports: [ "3000:3000" ]
    env_file: .env