name: Run Pytest

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        working-directory: backend
        run: |
          python -m pytest
